config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: 'posts#index'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  namespace :api do
		namespace :v1 do
			resources :posts, format: :json
		end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  skip_before_filter :authenticate_user

  def create
    user = User.find_by_email(params[:user_email])
    if user
      user.send_password_reset 
      redirect_to root_path, :notice => "Email sent with password reset instructions."  
    else
      redirect_to login_path, :notice => "Invalid email."
    end
    
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token(params[:id])
    if @user
      if @user.password_reset_sent_at < 2.hours.ago
        redirect_to login_path, :alert => "Password reset has expired."
      elsif @user.update_attributes(user_params)
        redirect_to root_url, :notice => "Password has been reset!"
      else
        render :edit
      end  
    else
      redirect_to login_path
    end    
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/views/password_resets/edit.html.slim
.container
  = form_for @user, :url => password_reset_path(params[:id]), :html => {:class => "form-signin"} do |f|
    h2.form-signin-heading Recuperar contraseña
    .login-wrap
      .user-login-info
        = f.password_field :password, :class => "form-control", :placeholder => "Contraseña"
        p.help-block = @user.errors[:password].first
        = f.password_field :password_confirmation, :class => "form-control", :placeholder => "Confirmar contraseña"
        p.help-block = @user.errors[:password_confirmation].first
      button.btn.btn-lg.btn-login.btn-block type="submit" Cambiar contraseña