config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: 'posts#index'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  namespace :api do
		namespace :v1 do
			resources :posts, format: :json
		end
  end
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top role="navigation" 
  .container
    .brand
      = link_to root_path, :class => "navbar-brand"
        | Pinocchio
    ul.nav.navbar-nav.navbar-right
      - if current_user      
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            = current_user.full_name
            span.caret
          ul.dropdown-menu role="menu" 
            li
              = link_to user_path current_user.id do
                = t("user.profile") 
            li
              = link_to logout_path do
                = t("actions.logout")
      - else 
        li
          = link_to login_path do
            = t("actions.login")
        li
          = link_to new_user_path do
            = t("actions.sign_up")

app/views/layouts/application.html.slim
doctype html
html
  head
    title Pinocchio
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" 
    script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"
    = csrf_meta_tags
  body
    = render "layouts/header"
    .container.content
      - flash.each do |name, msg|
        div class="alert alert-block #{flash_class(name)}"
          button.close.close-sm data-dismiss="alert" type="button" 
            span class="glyphicon glyphicon-remove"
          = msg            
      = yield